---
title: Začíname s Minecraft Pi
hero_image: images / banner.png
description: Získajte svoj prvý vkus programovania sveta Minecraft
original_url: https://raspberrypi.org/learning/getting-started-with-minecraft-pi
theme: žltá
duration: 2
listed: true
ingredient: false
copyedit: true
curriculum: 2, design-0, programovanie-2, phys-comp-0, výroba-0, komunita-0
interests: hry
technologies: krajta
site_areas: projekty
hardware: ''
software: krajta
version: 3
last_tested: 01.1.2017
steps:
  - 
    title: úvod
  - 
    title: Čo budete potrebovať
  - 
    title: Začíname s Minecraft Pi
  - 
    title: Spustite Minecraft
  - 
    title: Použite rozhranie programovania Python
  - 
    title: Pokles blokov počas chodu
  - 
    title: Hra s blokmi TNT
  - 
    title: Zábava s tečúcou lávou.
  - 
    title: Čo ďalej?
